### GET request to get all patients
### GET http://localhost:4000/patients
### GET http://localhost:4004/api/patients

GET http://lb-1380f550.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{token}}

###