### GET request to validate token
### GET http://localhost:4005/validate
### API GATEWAY
### GET http://localhost:4004/auth/validate

GET http://lb-1380f550.elb.localhost.localstack.cloud:4004/auth/validate
Authorization: Bearer {{token}}
###